### ISSUE TITLE
[Helm] Auto-reload when ConfigMap changed

### ISSUE THREAD

**Issue by chiefy** [oxyno-zeta/s3-proxy#119]
**Is your feature request related to a problem? Please describe.**
Currently if the s3-proxy `ConfigMap` is changed after deploy, the pod does not pick up changes until it is restarted.

**Describe the solution you'd like**
Either internally poll/detect change and reload config or use sidecar pattern

**Comment by oxyno-zeta** [comment]
Hello, on which version of Kubernetes are you ? 
The reload was working, long ( around 1 min from my tests) but working. 
Thanks in advance

**Comment by oxyno-zeta** [comment]
Hello again,

I've just tested on a minikube in 1.17 version and this is working perfectly (also tested on a real K8S cluster too). Kubernetes takes around 1 min to change the file and trigger the fsnotify event but it worked.

I must admit that I never tested with an older version. If there is a problem with an older version, I will mark the chart as not working for version <1.17.

Thanks for your answer.

**Comment by chiefy** [comment]
@oxyno-zeta let me try it again. I am on a `1.13` cluster and it didn't seem to be reloading but it may have just been my own impatience. I will close this for now and re-open if necessary. Thanks for all your help!

**Comment by chiefy** [comment]
...and yup, it's working...

```
{"level":"info","msg":"Reload configuration detected for file /proxy/conf/config.yaml","time":"2021-01-06T14:18:54Z"}
```

sorry for the false-report
