### ISSUE TITLE
 panic: label value "/\xff.js" is not valid UTF-8

### ISSUE THREAD

**Issue by alexdulin** [oxyno-zeta/s3-proxy#121]
**Describe the bug**
The server panics when trying to add a prometheus metric label that is not valid UTF-8, for example when the inbound request URL contains invalid characters.

**Expected behavior**
The server does not panic.

**Version and platform (please complete the following information):**
 - Platform: Docker
 - Version: 3.1.1

**Additional context**
Here is the log from the panic:
```
 panic: label value "/\xff.js" is not valid UTF-8
 
 -> github.com/prometheus/client_golang/prometheus.(*SummaryVec).WithLabelValues
 ->   /home/oxynozeta/dev/golang/pkg/mod/github.com/prometheus/client_golang@v1.9.0/prometheus/summary.go:603

    github.com/oxyno-zeta/s3-proxy/pkg/s3-proxy/metrics.(*prometheusClient).Instrument.func1.1
      /home/oxynozeta/dev/golang/src/github.com/oxyno-zeta/s3-proxy/pkg/s3-proxy/metrics/prometheus.go:44
    net/http.HandlerFunc.ServeHTTP
      /usr/local/go/src/net/http/server.go:2042
    github.com/go-chi/chi/middleware.RequestLogger.func1.1
      /home/oxynozeta/dev/golang/pkg/mod/github.com/go-chi/chi@v4.1.2+incompatible/middleware/logger.go:46
    net/http.HandlerFunc.ServeHTTP
      /usr/local/go/src/net/http/server.go:2042
    github.com/oxyno-zeta/s3-proxy/pkg/s3-proxy/server/middlewares.ImproveTracing.func1.1
      /home/oxynozeta/dev/golang/src/github.com/oxyno-zeta/s3-proxy/pkg/s3-proxy/server/middlewares/improve-tracing.go:28
    net/http.HandlerFunc.ServeHTTP
      /usr/local/go/src/net/http/server.go:2042
    github.com/go-chi/httptracer.Tracer.func1.1
      /home/oxynozeta/dev/golang/pkg/mod/github.com/go-chi/httptracer@v0.2.1/httptracer.go:80
    net/http.HandlerFunc.ServeHTTP
      /usr/local/go/src/net/http/server.go:2042
    github.com/go-chi/chi/middleware.Recoverer.func1
      /home/oxynozeta/dev/golang/pkg/mod/github.com/go-chi/chi@v4.1.2+incompatible/middleware/recoverer.go:37
    net/http.HandlerFunc.ServeHTTP
      /usr/local/go/src/net/http/server.go:2042
    github.com/go-chi/chi/middleware.RealIP.func1
      /home/oxynozeta/dev/golang/pkg/mod/github.com/go-chi/chi@v4.1.2+incompatible/middleware/realip.go:34
    net/http.HandlerFunc.ServeHTTP
      /usr/local/go/src/net/http/server.go:2042
    github.com/go-chi/chi/middleware.RequestID.func1
      /home/oxynozeta/dev/golang/pkg/mod/github.com/go-chi/chi@v4.1.2+incompatible/middleware/request_id.go:76
    net/http.HandlerFunc.ServeHTTP
      /usr/local/go/src/net/http/server.go:2042
    github.com/go-chi/chi/middleware.NoCache.func1
      /home/oxynozeta/dev/golang/pkg/mod/github.com/go-chi/chi@v4.1.2+incompatible/middleware/nocache.go:54
    net/http.HandlerFunc.ServeHTTP
      /usr/local/go/src/net/http/server.go:2042
    github.com/go-chi/chi/middleware.(*Compressor).Handler.func1
      /home/oxynozeta/dev/golang/pkg/mod/github.com/go-chi/chi@v4.1.2+incompatible/middleware/compress.go:213
    net/http.HandlerFunc.ServeHTTP
      /usr/local/go/src/net/http/server.go:2042
    github.com/go-chi/chi.(*Mux).ServeHTTP
      /home/oxynozeta/dev/golang/pkg/mod/github.com/go-chi/chi@v4.1.2+incompatible/mux.go:86
    net/http.serverHandler.ServeHTTP
      /usr/local/go/src/net/http/server.go:2843
    net/http.(*conn).serve
      /usr/local/go/src/net/http/server.go:1925
    created by net/http.(*Server).Serve
      /usr/local/go/src/net/http/server.go:2969
```

**Comment by oxyno-zeta** [comment]
Hello !

First of all, thanks for your issue.

The problem isn't coming from the s3-proxy product itself but from the prometheus golang client. In fact, Prometheus doesn't support non UTF-8 strings as described in this issue [805](https://github.com/prometheus/client_golang/issues/805).
According to this issue, it is better to have everything in utf-8. Isn't it possible for you ?

Can you tell me more info about the context of the request ? URL asked and with which encoding ?

For the moment, I don't see how I'm going to solve this without putting Prometheus servers in troubles :cry: .

**Comment by alexdulin** [comment]
Without verifying, I am pretty sure you could send a curl request with any non-utf8 characters in the request path and trigger this issue. The prometheus client is, understandably, rejecting the lables for a variety of reasons as outlined in that issue. The problem with the panic is not an issue with the request really, its due to using unsanitized user input for a metric label. If request paths are going to be used as labels, then they should be sanitized. Same reason you sanitize data that is going to be inserted into a SQL database.

Unrelated to the issue, but thank you for making this project. It is a fantastic peice of work that solves so many common problems.

**Comment by oxyno-zeta** [comment]
I'm sorry but I can't reproduce this case with cURL. When I try to request this kind of path:  "/traÖção" with cURL, the server got: "/tra%C3%96%C3%A7%C3%A3o" which is a perfect url encoded string and in UTF-8...

Can you give me an example with something that I can start ? Thanks !

PS: Thanks for your comment. I'm happy to see that this project is used. Don't forget to put a star :)
