### ISSUE TITLE
Support Range header

### ISSUE THREAD

**Issue by croustiPoulet** [oxyno-zeta/s3-proxy#182]
**Is your feature request related to a problem? Please describe.**
I am using this S3 proxy as a MPEG dash server backed by S3 storage. Video files are not split in chunks so the client is fetching the same file but with byte range. Sadly, this proxy does not handle this header feature so the whole file is fetched every team a client is requesting a video chunk. 

**Describe the solution you'd like**
When the GET API, the proxy could look for the "Range" option in the HTTP header and specify it to the AWS SDK when forwarding the request to the S3 storage.

**Comment by oxyno-zeta** [comment]
Hello @croustiPoulet ,

That's a good point and I saw your pull request for the feature. Thanks for all of this.
I'm sorry, I have a physical problem that doesn't allow me to develop for the moment... So, thanks for your pull request.

I will check your pull request now. 

Regards,

Oxyno-zeta

**Comment by oxyno-zeta** [comment]
This have been released ! Thanks for your contribution !
