### ISSUE TITLE
Status code routing

### ISSUE THREAD

**Issue by to0b** [oxyno-zeta/s3-proxy#24]
Hi, is it possible to add features for response handling?

I tried your proxy to provide a static angular website to an internal vpc only. We need to route back requests with 404 or 403 code to index.html and code 200. Or is this already possible and I'm not seeing the right config part for this?

Thanks in advance.

**Comment by oxyno-zeta** [comment]
Hello @to0b ,

First of all, thanks for your issue and your feedback.
Maybe next time, can you use the feature request template to help understanding ? :)

I will try to reformulate your request:

You have a bucket with:
- index.html
- app.js
- app.css

Actually, these requests will answer with "indexDocument" feature:
- / -> 200 index.html
- /app.js -> 200 app.js
- /app.css -> 200 app.css
- /not-found-path -> 404 Not found template is used
- /forbidden-path -> 403 Forbidden template is used

And you want that: 
- / -> 200 index.html
- /app.js -> 200 app.js
- /app.css -> 200 app.css
- /not-found-path -> 200 index.html
- /forbidden-path -> 200 index.html

Am I correct ?

Why not put your "index.html" content in the "not found" and "forbidden" template  ?

Regards

**Comment by to0b** [comment]
Yes you understood right. Put the Code into the template files should work but i think thats not a pretty Solution to host three index like files. It would be cooler to redirect on the given status Code back to a path or file with status Code 200. thanks :)

**Comment by oxyno-zeta** [comment]
Yes I agree on the fact that this isn't a pretty solution but this can be a short term solution waiting a new feature to support this.

I will think on a more global solution for redirect. For the moment, I haven't found a good way to manage redirects. 

My actual problem: We can put redirect files in bucket for example but how to manage this for errors ?
=> I need to think about this.

**Comment by to0b** [comment]
Yes, think its tricky too. 
As an example: In CloudFront you can define custom error pages for all http error codes and set a response page path with a response code. That would solve the angular routing problem. The routing is always done by angular and the url path coud be https://foo.bar/setting if you navigate from index.html to the settings page - but there is not a /setting file in the bucket and so the 404 pops up.

**Comment by oxyno-zeta** [comment]
Hello @to0b ,

I'm just wondering one thing. Can you explain me why a Forbidden error can conduct to "index.html" ?

A "Not found" error, I can understand. NGinX has this feature for this case. But a "Forbidden" no. Can you explain me the usecase ?

Thanks in advance,

**Comment by to0b** [comment]
I'm also not so familiar with angular development, i'm only the dev ops person to deploy it on aws.  :) But in my understanding, these error codes should be routed back to index.html that the angular router can catch up and route correctly to the requested path.

**Comment by oxyno-zeta** [comment]
Oh ok I see :) . I'm also from these guys.

I will try to do something for this. Don't know how now. I will search.

**Comment by oxyno-zeta** [comment]
Hello @to0b ,

I'm think I found a way to achieve what you need with a feature that I'm currently developping.
The feature is to load template per target (bucket) from bucket in order to override default templates. This will keep all status code but you can load files from bucket in case of "not found" or "forbidden" errors :).

Hope you will like it.

Regards,

**Comment by oxyno-zeta** [comment]
Hello @to0b ,

I finally released the 2.4.0 with the feature I told you. Hope this will solve your problem. Tell me if you have any problem.

Regards,
