### ISSUE TITLE
Accept self-signed certificate  S3 endpoint

### ISSUE THREAD

**Issue by ricardosantosmti** [oxyno-zeta/s3-proxy#242]
I'm connecting with the s3 backend, but as the certificate being used is self-signed.
Then I get the error "x509: certificate signed by unknown authority".

Is there a possibility to accept self-signed certificate for S3endpoint?

**Comment by oxyno-zeta** [comment]
Hello,

You can add your own certificate into the image just by creating another image like that:

Dockerfile:
```dockerfile
FROM oxynozeta/s3-proxy:VERSION

COPY mycert.crt /usr/local/share/ca-certificates/

RUN update-ca-certificates
```

Once it is done, you will be able connect your SSL endpoint without any other configuration.

Regards,

Oxyno-zeta

**Comment by ricardosantosmti** [comment]
Thanks.
