### ISSUE TITLE
How to operate s3-proxy behind a reverse http proxy?

### ISSUE THREAD

**Issue by gsalvatella** [oxyno-zeta/s3-proxy#268]
Using an nginx reverse proxy to route https into s3-proxy (localhost:8080) with SSL certs server by nginx as well. However the port is still open, so using it explicitly will render an insecure connection... I thought using the `internalServer` port was the solution, but I may have missunderstood?

**Comment by gsalvatella** [comment]
I simply have the proxy at the default port and nginx configured as a reverse proxy with:
```
server {
  listen 443 ssl http2;
  server_name  example.com;
}
server {
  listen 443 ssl http2;
  server_name  proxy.example.com;
  proxy_pass http://localhost:8080; # If you are using docker-compose this would be the hostname i.e. minio
}
```
Now https://proxy.example.com works fine, but http://example.com:8080 will connect directly to the s3-proxy with an insecure connection...

**Comment by gsalvatella** [comment]
Logs from connection to both hostnames
```
time="2022-04-08T17:48:02Z" level=info msg="Server listening on :8080"
time="2022-04-08T17:48:16Z" level=info msg="no resource declared => skip authentication" client_ip=xxx.xx.xx.xx http_method=GET http_proto=HTTP/1.1 http_scheme=https remote_addr=xxx.xx.xx.xx req_id=s3-proxy/SKZ8wbZAiX-000001 uri="https://proxy.example.com/" user_agent="Mozilla/5.0 (X11; Linux x86_64; rv:99.0) Gecko/20100101 Firefox/99.0"
time="2022-04-08T17:48:16Z" level=info msg="request complete" client_ip=xxx.xx.xx.xx http_method=GET http_proto=HTTP/1.1 http_scheme=https remote_addr=xxx.xx.xx.xx req_id=s3-proxy/SKZ8wbZAiX-000001 resp_bytes_length=481 resp_elapsed_ms=3.258683 resp_status=200 uri="https://proxy.example.com/" user_agent="Mozilla/5.0 (X11; Linux x86_64; rv:99.0) Gecko/20100101 Firefox/99.0"
time="2022-04-08T17:48:29Z" level=info msg="no resource declared => skip authentication" client_ip="xxx.xx.xx.xx:45634" http_method=GET http_proto=HTTP/1.1 http_scheme=http remote_addr="xxx.xx.xx.xx:45634" req_id=s3-proxy/SKZ8wbZAiX-000002 uri="http://example.com:8080/" user_agent="Mozilla/5.0 (X11; Linux x86_64; rv:99.0) Gecko/20100101 Firefox/99.0"
time="2022-04-08T17:48:29Z" level=info msg="request complete" client_ip="xxx.xx.xx.xx:45634" http_method=GET http_proto=HTTP/1.1 http_scheme=http remote_addr="xxx.xx.xx.xx:45634" req_id=s3-proxy/SKZ8wbZAiX-000002 resp_bytes_length=501 resp_elapsed_ms=6.227646 resp_status=200 uri="http://example:8080/" user_agent="Mozilla/5.0 (X11; Linux x86_64; rv:99.0) Gecko/20100101 Firefox/99.0"
time="2022-04-08T17:48:29Z" level=error msg="request complete" client_ip="xxx.xx.xx.xx:45634" http_method=GET http_proto=HTTP/1.1 http_scheme=http remote_addr="xxx.xx.xx.xx:45634" req_id=s3-proxy/SKZ8wbZAiX-000003 resp_bytes_length=19 resp_elapsed_ms=1.824067 resp_status=404 uri="http://example.com:8080/favicon.ico" user_agent="Mozilla/5.0 (X11; Linux x86_64; rv:99.0) Gecko/20100101 Firefox/99.0"
```

**Comment by oxyno-zeta** [comment]
Hello,

Seems that everything is working. 

What I don't understand is why are you requesting `http://example.com:8080` and not `https://example.com` ?
Your NGinX instance is listening on 443 port only. Insecure is coming from the fact that you are requesting on HTTP or insecure certificate ?

Note: Why there isn't any proxy pass on example.com ?

**Comment by gsalvatella** [comment]
Hi, excuse me for the late reply.

So I have a service (let's say a web page) in `example.com`. This one goes through the standard 443. On the other hand, I have `proxy.example.com`, which is proxied to s3-proxy. This one is also accessed through 443 and works fine. However, since the DNS for `example.com` points to the server machine, doing `http://example.com:8080` bypasses the proxy and connects directly to port `8080` where s3-proxy is listening via insecurely.

**Comment by oxyno-zeta** [comment]
Hello,

No worry.

Ah ok I understand now what you are looking for.
The internal server isn't for that I'm sorry. 
S3-Proxy is managing hosts like servers and locations in NGinX. If you have put a host on your target, you have to create another target with the same bucket. 

I'm answering quickly through phone, tell me if it's unclear.

Can you provide me the configuration you built for the app ? In order to help you better for that if you want to.

Regards,
