### ISSUE TITLE
How to use s3-proxy with AWS named profiles

### ISSUE THREAD

**Issue by gites** [oxyno-zeta/s3-proxy#278]
How to configure s3-proxy to use AWS named profiles configured in `$HOME/.aws/config` and `$HOME/.aws/credentials` files ?

**Comment by oxyno-zeta** [comment]
I was afraid of this. I'm sorry but you will have to change to environment variables or files containing plain secrets. 
Or you can contribute and create the support for that.

Regards,

Oxyno-zeta

**Comment by gites** [comment]
I was able to configure s3-proxy to use named profiles. The secret souce was setting `AWS_SDK_LOAD_CONFIG`  (https://docs.aws.amazon.com/sdk-for-go/api/aws/session/)
The final config looks like this:

```
          - name: AWS_SDK_LOAD_CONFIG
            value: "true"
          - name: AWS_PROFILE
            value: some-profile-name
```
