### ISSUE TITLE
Using s3cmd

### ISSUE THREAD

**Issue by Michael-Amann** [oxyno-zeta/s3-proxy#308]
Hello,

Is it possible to use s3cmd with this proxy? https://github.com/s3tools/s3cmd
Or is that not possible because s3-proxy is not an S3 endpoint proxy, see https://github.com/oxyno-zeta/s3-proxy/issues/255#issuecomment-1062932087?

Thank and regards,
Michael

**Comment by oxyno-zeta** [comment]
Hello,

No that's not possible, I'm sorry. This is a Reverse proxy with S3 as storage, not a S3 Endpoint proxy.
Minio have the support for a S3 Endpoint proxy if I remember correctly.

Regards,

Oxyno-zeta

**Comment by Michael-Amann** [comment]
Hi @oxyno-zeta 

thank you for your response!
Are there any plans to add this feature in the future?

Regards
Michael

**Comment by oxyno-zeta** [comment]
Hello !

I'm afraid this isn't planned for the moment. I'm reflecting about this for a while but never finished... Sorry.

Maybe in another project ;)

Regards,

Oxyno-zeta

**Comment by Michael-Amann** [comment]
thank you!
