### ISSUE TITLE
Let the docker image build itself

### ISSUE THREAD

**Issue by EnigmaCurry** [oxyno-zeta/s3-proxy#328]
**Is your feature request related to a problem? Please describe.**
I would like to build the docker image without first needing to build it on the host.

**Describe the solution you'd like**
I would like to build the image without dependencies, like:
```
docker build -t s3-proxy .
```

**Describe alternatives you've considered**
I have made a multi-stage Dockerfile that builds the application and image in one step: see #327 

**Additional context**

For example its really nice and dependency free from docker-compose, just give it the URL/branch and it will build it itself:

```
# docker-compose.yaml
services:
  s3-proxy:
    build:
      context: https://github.com/EnigmaCurry/s3-proxy.git#self-buildable
```

**Comment by oxyno-zeta** [comment]
From my quick tests, the code you provided in your pull request seems to not be compatible with Goreleaser.

I need to check more details.
