### ISSUE TITLE
Add support for filesystem as a target

### ISSUE THREAD

**Issue by aslafy-z** [oxyno-zeta/s3-proxy#332]
**Is your feature request related to a problem? Please describe.**
I'd like to expose a filesystem directory as an S3 bucket.
Minio Gateway is now deprecated so I won't use it and I'm looking for an alternative.

**Describe the solution you'd like**
I'd love a configurable target to a directory so I can use this project as a s3 server.

**Describe alternatives you've considered**
https://github.com/gaul/s3proxy is an option. I'd love to get an Golang alternative of this nice java tool.

**Comment by oxyno-zeta** [comment]
Hello @aslafy-z ,

I'm sorry but this project haven't been done to be used that way. It is a web reverse proxy backed by s3. It doesn't implement the full s3 api.
The gaul/s3-proxy is the good option for you sorry.

Regards,

Oxyno-zeta
