### ISSUE TITLE
Update project to resolve dependabot and renovate suggestions

### ISSUE THREAD

**Issue by fostermi** [oxyno-zeta/s3-proxy#404]
Would it be possible to update this project to be able to keep it up-to-date and incorporate changes suggested by dependabot and renovate?

**Comment by oxyno-zeta** [comment]
Hello, 

Thanks for your issue.

I'm updating the project from time to time yes. Do you need a particular fix ?

Oxyno-zeta

**Comment by fostermi** [comment]
No particular fix. Just wanted to make sure that the project was keeping up-to-date with any dependencies in case of security issues. Thanks for updating!
