### ISSUE TITLE
Does multi-part upload work?

### ISSUE THREAD

**Issue by JuroOravec** [oxyno-zeta/s3-proxy#443]
**Describe the bug**
I was trying to use s3-proxy with [Loki helm chart](https://github.com/grafana/loki/tree/main/production/helm/loki) ([thread on setting up Loki with S3](https://github.com/grafana/loki/issues/8524)).

Unfortunately I don't have to stack trace, but I was getting error which said "Request isn't multi-part". And the error was complaining that the response couldn't be unmarshaled. The response was an XML/HTML doc with `<html>` tags, and the error claimed it expected `<Error>` tags.

Sorry I don't have more info, I didn't look further into this problem, since there were other problems with the Loki setup. But wanted to report this in case more people come across this or google for this error.

I was using the helm chart version: 2.19.0.

**Comment by oxyno-zeta** [comment]
Hello,

This is "normal" per se because this project isn't an API proxy for S3 but a "S3 Reverse Proxy with GET, PUT and DELETE methods and authentication". That's why it won't work as you want and that's why this error is raised.

Have a nice rest of your day !

Oxyno-zeta
