### ISSUE TITLE
Feature to proxy XML responses as-is

### ISSUE THREAD

**Issue by krokicki** [oxyno-zeta/s3-proxy#462]
**Is your feature request related to a problem? Please describe.**
It looks like the folder listing output is either HTML or JSON. To use this with the AWS Java API, I need to get the XML output that AWS produces.  

**Describe the solution you'd like**
A way to turn off HTML/JSON and just proxy the response from AWS as-is.

**Comment by oxyno-zeta** [comment]
Hello,

I'm sorry but I don't get the aim of this.

If you want to consume the AWS API without any authentication, this proxy isn't made for this purpose. It is a web proxy.

Have a good day !

Regards,

Oxyno-zeta

**Comment by krokicki** [comment]
The aim would be to expose a subsets of private buckets for public access. The S3 API is a de-facto standard and it is supported by many products, and this feature would make this proxy compatible with all of those products. Right now it is only compatible with things that can read the JSON format. 

I understand if this is outside your scope though. Thanks for considering!
