### ISSUE TITLE
Could not run docker container due config file not found

### ISSUE THREAD

**Issue by devopsman** [oxyno-zeta/s3-proxy#56]
Hello friend!

I'm trying to run your s3-proxy tool from docker but getting this error:

$ docker run -d --name s3-proxy -p 8080:8080 -p 9090:9090 -v $PWD/config:/config oxynozeta/s3-proxy
fe4fb5a7c43324170e8879fd9516fa860556dc166e8043bec3baef2e4bcee582

$ docker logs fe4fb5a7c43324170e8879fd9516fa860556dc166e8043bec3baef2e4bcee582
{"level":"fatal","msg":"Config File \"config\" Not Found in \"[/conf /]\"","time":"2020-05-22T11:40:54Z"}

However I have config directory in my $HOME dir with config.yml inside:
$ ls -la $HOME/config/config.yaml
-rw-rw-r-- 1 db db 6291 May 22 14:17 /home/db/config/config.yaml

Any ideas what can be wrong here?

Thank you

**Comment by oxyno-zeta** [comment]
Hello @devopsman ,

Can you try that command instead ?

```bash
docker run -d --name s3-proxy -p 8080:8080 -p 9090:9090 -v /home/db/config:/conf oxynozeta/s3-proxy
```

You show me that there is an error in the documentation by the way. Thanks !

The previous command should work.

Regards,

**Comment by devopsman** [comment]
Hello Havrileck,

thanks for fixing that.

I managed to run container fine but still got some questions..

Is there any chance to chat with you for quick help?

Your proxy looks very promising and I would like to try it for my per project.

Appreciate if you can provide any contacts of yours.

Thanks,
Andrii

**Comment by oxyno-zeta** [comment]
Hello @devopsman ,

I'm sorry but I don't have any private chat. The only thing I can provide is a Gitter [here](https://gitter.im/s3-proxy/community?utm_source=share-link&utm_medium=link&utm_campaign=share-link) or to continue on this issue.
Continue on this issue can be interesting for other people too :) and I prefer this one too.

Tell me which one you prefer.

Thanks !

**Comment by devopsman** [comment]
Hello @oxyno-zeta ,

I'm fine to speak here :-)

I think I managed most of my issues by setting correct config.yaml,
now can do basic things to my files through proxy.

The only question I could not find logs for s3-proxy neither option for setting log files path in config.

Is there an ability to gather logs for s3-proxy server?

Thank you,
Andrii

**Comment by oxyno-zeta** [comment]
Hello @devopsman ,

Cool news :). Happy to read that.

I'm sorry but no, there is actually no way to put logs in a file directly from the application. Only stdout/stderr is available. You can look at them by running this command:
```bash
docker logs s3-proxy
```

Maybe this can be a good enhancement ! I will think about this.

Regards,
Oxyno-zeta

**Comment by devopsman** [comment]
Hey @oxyno-zeta ,

thanks for hint, I'm fine using docker logs for now!

Anyway you have a star!

Keep up a good work ;-)

**Comment by oxyno-zeta** [comment]
Hello @devopsman ,

Thanks for the star and your message :) . 

Regards,
